# https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html

if({CMAKE_MAJOR_VERSION} LESS 3 OR ${CMAKE_MINOR_VERSION} LESS 16)
    SET(CMAKE_UNITY_BUILD OFF)
else()
    if(DEFINED CMAKE_UNITY_BUILD AND CMAKE_UNITY_BUILD STREQUAL "OFF")
        SET(CMAKE_UNITY_BUILD OFF)
    else()
        SET(CMAKE_UNITY_BUILD ON)
    endif()
endif()

if(CMAKE_UNITY_BUILD STREQUAL "ON")
    if(NOT DEFINED CMAKE_UNITY_BUILD_BATCH_SIZE)
        set(CMAKE_UNITY_BUILD_BATCH_SIZE 16)
    endif()
    message(STATUS "UNITY_BUILD IS ENABLED FOR THIS PROJECT:${PROJECT_NAME}")
    message(STATUS "UNITY_BUILD BATCH SIZE IS:" ${CMAKE_UNITY_BUILD_BATCH_SIZE})
endif()
